### ISSUE TITLE
Path folders for in-path parameters

### ISSUE THREAD

**Issue by brianwestphal** [kogosoftwarellc/open-api#344]
When specifying a paths root, in-path parameters, files need to be named like ":variable-name"

example:
```
  /my-path/{id}:
    get:
      summary: Gets stuff
      parameters:
        - name: id
          in: path
          description: The ID of the stuff to get
          required: true
          schema:
            type: string
```

the handler filename needs to be called "my-path/:id.js".

1. This isn't clear from the documentation
1. apiDoc and validateResponse never get set on these requests / responses, making it more painful to add response validation to these handlers
