### ISSUE TITLE
securityDefinitions documentation

### ISSUE THREAD

**Issue by nasht00** [kogosoftwarellc/open-api#351]
Where are the rules defined, regarding what I can write in the `securityDefinitions` yml ?

For example when my definition is called `Bearer` it seems to only accept:

```
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
```

But what if it's not an API key? I can't find the list nor logic behind what it valid or not...
