### ISSUE TITLE
[openapi-jsonschema-parameters] No properties copied over for parameters of type object

### ISSUE THREAD

**Issue by TomaszChrosniak** [kogosoftwarellc/open-api#593]
`openapi-jsonschema-parameters` strips the `properties` from the schema for things like query and path params.

I'm mostly interested in the former, as this is causing issues in my particular use case of validating the pagination query parameters for a JSON:API request ([spec](https://jsonapi.org/format/1.0/#auto-id--pagination)).

Please find the below snippet from our OAI3 schema for the `page` query parameter:
```yaml
components:
  parameters:
    PageQueryParam:
      name: page
      in: query
      schema:
        description: |
          Although JSON:API doesn't enforce any specific pagination strategy, it does reserve the `page` query parameter
          and suggests using an object with fields corresponding to parameters relating to the selected pagination strategy.
        type: object
        externalDocs:
          description: JSON:API Pagination
          url: https://jsonapi.org/format/1.0/#auto-id--pagination
        properties:
          offset:
            type: integer
          limit:
            type: integer
            maximum: 100 # TODO: magic number
```

At the moment `ajv` in the request validator is not given the `properties` of the object, so it can only validate the type of the `page` query param, which in this case is `object`. This results in incorrect values for `page[offset]` or `page[limit]` passing the validation done by `openapi-request-validator`.

~~I will issue a PR later today once I have the chance, but my sort-of quickfix solution is to add `properties` to the `VALIDATION_KEYWORDS` array.~~ See edit below.

https://github.com/kogosoftwarellc/open-api/blob/6323130dfe8e4c895ad88267333e20db20563860/packages/openapi-jsonschema-parameters/index.ts#L44-L65

Please share your thoughts.

EDIT:

Okay, yeah, just adding `properties` into the `VALIDATION_KEYWORDS` won't suffice as it will just copy the properties without converting them to JSON Schema. Looking further into it.
