### ISSUE TITLE
express-openapi not coercing parameters that use a $ref in their schema

### ISSUE THREAD

**Issue by chadxz** [kogosoftwarellc/open-api#647]
When I use a parameter like this:

```yaml
parameters:
  - name: flag
    in: query
    schema:
      $ref: '#/components/schemas/SomeFlag'
```

where the component looks like this:

```yaml
components:
  schemas:
    SomeFlag:
      type: boolean
```

The parameter that ends up in my controller action hasn't been parsed as the appropriate type. If i inline the schema it works as expected.

Here's a minimal reproduction of my issue: https://github.com/chadxz/param-ref-repro

When i was debugging the issue it looks like there's no support for $ref in openapi-request-coercer, but I don't know if the schema refs should have been resolved prior to getting to that library or not.

**Comment by schristley** [comment]
I ran into a similar problem using version 6.0.0 on npm, specifically the `nullable` flag wasn't being recognized for a field in the requestBody.

```
      requestBody:
        content:
          'application/json':
            schema:
              required:
                - project
              properties:
                project:
                  $ref: '#/components/schemas/Project'
```

where the component looks like this:

```
components:
  schemas:
    Project:
      type: object
      properties:
        owner:
          description: Username that owns the project.
          type: string
          nullable: true
```

sending this data

```
{"project":{"owner":null}}
```

gives this error.

```
[
  {
    "path": "project.owner",
    "errorCode": "type.openapi.requestValidation",
    "message": "should be string",
    "location": "body"
  }
]
```

@chadxz As I workaround, I found using [json-schema-ref-parser](https://www.npmjs.com/package/json-schema-ref-parser) works. Essentially dereference all of the `$ref` in the API spec before passing to initialize.
