### ISSUE TITLE
Allow ability to disable "servers" property from automatically forwarding all requests

### ISSUE THREAD

**Issue by Nik-Novak** [kogosoftwarellc/open-api#653]
Currently, if you specify a server property in the api spec like so:
```
servers:
  - url: https://services.mydomain.com/my-service
    description: External endpoint
  - url: http://internal-services/my-service
    description: Internal endpoint
```

All requests to the express server need to be prepended with a /my-service/PATH.
This is rather annoying for hosting local/test versions of the api, or cases like mine where a nginx server does the routing. The server should have the option to follow only the strict paths in /paths, instead of automatically applying /my-service/ as a requirement to the path just due to the fact that it si listed under services.

Unfortunately, to be able to generate proper documentation, often that server property is necessary, otherwise I would exclude it to prevent this automatic-forwarding behaviour. Could a flag like `ignoreServerPaths` be added to accomplish this?
