### ISSUE TITLE
External refs not captured in parameters for request validation

### ISSUE THREAD

**Issue by sazazi** [kogosoftwarellc/open-api#887]
For `openapi-request-validator`, if you pass parameters to the `OpenAPIRequestValidator` with external refs, and do not include that parameter in the request you're validating, there will be no errors which is not as expected.

e.g.

```
const validator = new OpenAPIRequestValidator({
    parameters: [
      {
        $ref: 'http://example.com/parameters/headers.yml#/parameters/xToken',
      }
  ]
```

where http://example.com/parameters/headers.yml#/parameters/xToken is:
``` 
 xToken:
    name: X-Token
    in: header
    description: Authentication token.
    schema:
      type: string
    required: true
```

Validating the request as:
```
validator.validateRequest({
  headers: {},
  body: {},
  params: {},
})
```
will still pass, despite the required header not being present. However, when you add the xToken header parameter directly as an argument, and then validate the request, it will fail as expected.

Is this something that has been missed?
